name: Update media.json

on:
  schedule:
    # daily at 14:00 WIB
    - cron: '0 7 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install (no dependencies)
        run: npm install
      - name: Update media.json
        run: npm run fetch-media
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add media.json
          git commit -m "Update media.json"
          git push
